### ISSUE TITLE
Highlight trailing space only

### ISSUE THREAD

**Issue by abitdodgy** [disq/HighlightWhitespaces#11]
Is it possible to highlight trailing space only? For example:

```ruby
class Me
  def initialize
    something
  end
end
```

The spaces between the line start and `def`, `something`, and `end` are highlighted. But I'm only interested in trailing whitespace, or orphaned whitespace (whitespace on a blank line with no code).

Is there a way to do this?

**Comment by disq** [comment]
Fixed in 1.1.3, see the new settings file options
